// <auto-generated />
using System;
using Kaizen.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaizen.Core.Migrations
{
    [DbContext(typeof(KaizenDbContext))]
    [Migration("20231022135430_FixTimeSlot")]
    partial class FixTimeSlot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kaizen.Core.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("Kaizen.Core.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Kaizen.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Schooler"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Parent"
                        });
                });

            modelBuilder.Entity("Kaizen.Core.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("GradeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Kaizen.Core.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Kaizen.Core.Models.TeacherOfSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TeacherOfSubjects");
                });

            modelBuilder.Entity("Kaizen.Core.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BeginTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginTime = new TimeSpan(0, 9, 0, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 9, 45, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            BeginTime = new TimeSpan(0, 9, 55, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 10, 40, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            BeginTime = new TimeSpan(0, 10, 50, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 11, 35, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            BeginTime = new TimeSpan(0, 11, 45, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            BeginTime = new TimeSpan(0, 13, 0, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 13, 45, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            BeginTime = new TimeSpan(0, 13, 50, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 14, 35, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            BeginTime = new TimeSpan(0, 14, 35, 0, 0),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 15, 20, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            BeginTime = new TimeSpan(0, 9, 0, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 9, 45, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            BeginTime = new TimeSpan(0, 9, 55, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 10, 40, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            BeginTime = new TimeSpan(0, 10, 50, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 11, 35, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            BeginTime = new TimeSpan(0, 11, 45, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            BeginTime = new TimeSpan(0, 13, 0, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 13, 45, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            BeginTime = new TimeSpan(0, 13, 50, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 14, 35, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            BeginTime = new TimeSpan(0, 14, 35, 0, 0),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 15, 20, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            BeginTime = new TimeSpan(0, 9, 0, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 9, 45, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            BeginTime = new TimeSpan(0, 9, 55, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 10, 40, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            BeginTime = new TimeSpan(0, 10, 50, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 11, 35, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            BeginTime = new TimeSpan(0, 11, 45, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            BeginTime = new TimeSpan(0, 13, 0, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 13, 45, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            BeginTime = new TimeSpan(0, 13, 50, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 14, 35, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            BeginTime = new TimeSpan(0, 14, 35, 0, 0),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 15, 20, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            BeginTime = new TimeSpan(0, 9, 0, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 9, 45, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            BeginTime = new TimeSpan(0, 9, 55, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 10, 40, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            BeginTime = new TimeSpan(0, 10, 50, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 11, 35, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            BeginTime = new TimeSpan(0, 11, 45, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            BeginTime = new TimeSpan(0, 13, 0, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 13, 45, 0, 0)
                        },
                        new
                        {
                            Id = 27,
                            BeginTime = new TimeSpan(0, 13, 50, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 14, 35, 0, 0)
                        },
                        new
                        {
                            Id = 28,
                            BeginTime = new TimeSpan(0, 14, 35, 0, 0),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 15, 20, 0, 0)
                        },
                        new
                        {
                            Id = 29,
                            BeginTime = new TimeSpan(0, 9, 0, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 9, 45, 0, 0)
                        },
                        new
                        {
                            Id = 30,
                            BeginTime = new TimeSpan(0, 9, 55, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 10, 40, 0, 0)
                        },
                        new
                        {
                            Id = 31,
                            BeginTime = new TimeSpan(0, 10, 50, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 11, 35, 0, 0)
                        },
                        new
                        {
                            Id = 32,
                            BeginTime = new TimeSpan(0, 11, 45, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 33,
                            BeginTime = new TimeSpan(0, 13, 0, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 13, 45, 0, 0)
                        },
                        new
                        {
                            Id = 34,
                            BeginTime = new TimeSpan(0, 13, 50, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 14, 35, 0, 0)
                        },
                        new
                        {
                            Id = 35,
                            BeginTime = new TimeSpan(0, 14, 35, 0, 0),
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 15, 20, 0, 0)
                        });
                });

            modelBuilder.Entity("Kaizen.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin",
                            FirstName = "admin",
                            LastName = "admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("Kaizen.Core.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Kaizen.Core.Models.Schedule", b =>
                {
                    b.HasOne("Kaizen.Core.Models.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Core.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Core.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Core.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");

                    b.Navigation("Grade");

                    b.Navigation("Subject");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Kaizen.Core.Models.TeacherOfSubject", b =>
                {
                    b.HasOne("Kaizen.Core.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kaizen.Core.Models.User", b =>
                {
                    b.HasOne("Kaizen.Core.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Kaizen.Core.Models.UserRole", b =>
                {
                    b.HasOne("Kaizen.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kaizen.Core.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
