name: Build and Deploy on digital ocean
on:
  push: 
    branches: [master]

jobs:
  build_main_api: 
    name: Build Main API [.net]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in Docker HUB
        uses: docker/login-action@v1
        with:
          username: chernikov
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build docker 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chernikov/courses_kaizen_main_api
  build_ng: 
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Log in Docker HUB
          uses: docker/login-action@v1
          with:
            username: chernikov
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        - name: Build docker 
          uses: docker/build-push-action@v2
          with:
            context: ./Kaizen.Ng
            file: ./Kaizen.Ng/Dockerfile
            push: true
            tags: chernikov/courses_kaizen_ng
  deploy: 
    runs-on: ubuntu-latest
    needs: [build_main_api, build_ng]
    steps: 
      - name: Login via SSH and call docker-compose 
        uses: appleboy/ssh-action@v0.1.3
        with: 
          host: 164.92.226.106
          username: root
          password: ${{ secrets.DIGITAL_OCEAN_DROPLET_PASSWORD }}
          script: |
           cd /home
           docker-compose down
           docker-compose pull
           docker-compose up --detach



